<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, minimum-scale=0.8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="node_modules/sweetalert2/dist/sweetalert2.min.css">
</head>
<body>
<div class="navBar">
    <div class="navBarLeft">
        <a class="regularText" href="#">Blog écrivain</a>
    </div>
    <div class="navBarRight">
        <a class="regularText" href="#">Accueil</a>
        <a class="regularText" href="#">Tickets</a>
        <a class="regularText" href="#">Login</a>
    </div>
</div>
<div class="pageContainer">
    <div class="accountContainer">
        <div class="loginContainer">
            <h1 class="regularText accountTitle">
                Connexion
            </h1>
            <div class="formContainer">
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Identifiant
                    </h2>
                    <input id="l-email" class="input" type="text"/>
                    <p class="help">
                        Entrez votre adresse mail ou votre nom d'utilisateur.
                    </p>
                </div>
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Mot de passe
                    </h2>
                    <input id="l-password" class="input" type="password"/>
                </div>
                <div id="button-login" class="buttonContainer">
                    Se connecter
                </div>
            </div>
        </div>
        <div class="registerContainer">
            <h1 class="regularText accountTitle">
                Enregistrement
            </h1>
            <div class="formContainer">
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Adresse mail
                    </h2>
                    <input id="r-email" class="input" type="email">
                </div>
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Nom d'utilisateur
                    </h2>
                    <input id="r-username" class="input" type="text">
                </div>
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Mot de passe
                    </h2>
                    <input id="r-password" class="input" type="password">
                </div>
                <div class="formSection">
                    <h2 class="formSectionTitle regularText" isRequired="true">
                        Confirmez votre mot de passe
                    </h2>
                    <input id="r-confirmPassword" class="input" type="password">
                </div>
                <div id="button-register" class="buttonContainer">
                    S'enregistrer
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="node_modules/sweetalert2/dist/sweetalert2.all.js"></script>
<script>
    /**
     * Login
     **/
    $('#button-login').click(function () {
        let email = $('#l-email').val();
        let password = $('#l-password').val();
        if (email && password) {
            $.post('account',
                {
                    type: 'login',
                    email: email,
                    password: password
                },
                function (msg) {
                    if (msg) return errorMessage(msg);
                    return successMessage('Vous êtes désormais connecté.');
                }
            );
        }
        return errorMessage('Merci de bien vouloir remplir tous les champs.');
    });

    /**
     * Register
     **/
    $('#button-register').click(function() {
        // Datas
        let email = $('#r-email').val();
        let username = $('#r-username').val();
        let password = $('#r-password').val();
        let confirmPassword = $('#r-confirmPassword').val();

        // Conditions
        if (email && username && password && confirmPassword) {
            if (validateEmail(email)) {
                if (password === confirmPassword) {
                    $.post('account',
                        {
                            type: 'register',
                            email: email,
                            username: username,
                            password: password,
                            confirmPassword: confirmPassword
                        },
                        function (msg) {
                            if (msg) return errorMessage(msg);
                            return successMessage('Votre compte à bien été crée.');
                        }
                    );
                    return;
                }
                return errorMessage('Vos deux mot de passe ne correspondent pas.');
            }
            return errorMessage('Veuillez entrer une adresse mail valide.');
        }
        return errorMessage('Veuillez remplir tout les champs.');
    });

    /**
     * Validate email with regex test
     * @param email
     * @return {boolean}
     */
    function validateEmail(email) {
        const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }

    /**
     * Send error notifications
     * @param msg
     * @return {*}
     */
    function errorMessage(msg) {
        return Swal.fire({
            icon: 'error',
            title: 'Erreur',
            text: msg
        })
    }

    /**
     * Send success notifications
     * @param msg
     * @return {*}
     */
    function successMessage(msg) {
        return Swal.fire({
            icon: 'success',
            title: 'Success',
            text: msg
        })
    }
</script>
</body>
</html>