<div class="pageContainer">
    <?php if($this->isLogin()): ?>
        <div class="accountLogged">
            <div class="profileContainer">
                <div class="profileCard">
                    <div class="profileAvatar">
                        <img src="<?php echo $this->getHost() ?>/assets/avatar/avatar.png">
                    </div>
                    <h2 class="regularText"><?php echo $this->getUsername(); ?></h2>
                    <a href="logout" class="buttonContainer logout">Déconnexion</a>
                </div>
            </div>
            <div class="statisticsContainer">
                <div class="stat">
                    <div tooltip="Chapitres lu" class="statIcon">
                        <img src="<?php echo $this->getHost() ?>/assets/imgs/icons/book-open.png" alt="open-book">
                    </div>
                    <h2 class="regularText"><?php echo $chaptersViewCount; ?></h2>
                </div>
                <div class="stat">
                    <div tooltip="Commentaires" class="statIcon">
                        <img src="<?php echo $this->getHost() ?>/assets/imgs/icons/comments.png" alt="comments">
                    </div>
                    <h2 class="regularText"><?php echo $commentsCount; ?></h2>
                </div>
                <div class="stat">
                    <div tooltip="Chapitres écrit" class="statIcon">
                        <img src="<?php echo $this->getHost() ?>/assets/imgs/icons/write.png" alt="write">
                    </div>
                    <h2 class="regularText"><?php echo $chaptersCount; ?></h2>
                </div>
            </div>
            <?php if($this->isAdmin()): ?>
                <a href="<?php echo $this->getHost() ?>/new">
                    <div class="buttonContainer accountButton">
                        Ajouter un nouveau chapitre
                    </div>
                </a>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <div class="accountContainer">
            <div class="loginContainer">
                <h1 class="regularText accountTitle">
                    Connexion
                </h1>
                <div class="formContainer">
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Adresse mail
                        </h2>
                        <input id="l-email" class="input" type="text"/>
                    </div>
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Mot de passe
                        </h2>
                        <input id="l-password" class="input" type="password"/>
                    </div>
                    <div id="button-login" class="buttonContainer">
                        Se connecter
                    </div>
                </div>
            </div>
            <div class="registerContainer">
                <h1 class="regularText accountTitle">
                    Enregistrement
                </h1>
                <div class="formContainer">
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Adresse mail
                        </h2>
                        <input id="r-email" class="input" type="email">
                    </div>
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Nom d'utilisateur
                        </h2>
                        <input id="r-username" class="input" type="text">
                    </div>
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Mot de passe
                        </h2>
                        <input id="r-password" class="input" type="password">
                        <p class="help">
                            Votre mot de passe doit contenir au moins 7 caractères.
                        </p>
                    </div>
                    <div class="formSection">
                        <h2 class="formSectionTitle regularText" isRequired="true">
                            Confirmez votre mot de passe
                        </h2>
                        <input id="r-confirmPassword" class="input" type="password">
                    </div>
                    <div id="button-register" class="buttonContainer">
                        S'enregistrer
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<script>
    /**
     * Login
     **/
    $('#button-login').click(function () {
        let email = $('#l-email').val();
        let password = $('#l-password').val();
        if (email && password) {
            $.post('account',
                {
                    type: 'login',
                    email: email,
                    password: password
                },
                function (msg) {
                    if (msg) return errorMessage(msg);
                    location.reload();
                }
            );
        } else {
            return errorMessage('Merci de bien vouloir remplir tous les champs.');
        }
    });

    /**
     * Register
     **/
    $('#button-register').click(function() {
        // Datas
        let email = $('#r-email').val();
        let username = $('#r-username').val();
        let password = $('#r-password').val();
        let confirmPassword = $('#r-confirmPassword').val();

        // Conditions
        if (email && username && password && confirmPassword) {
            if (validateEmail(email)) {
                if (password === confirmPassword) {
                    $.post('account',
                        {
                            type: 'register',
                            email: email,
                            username: username,
                            password: password,
                            confirmPassword: confirmPassword
                        },
                        function (msg) {
                            if (msg) return errorMessage(msg);
                            return successMessage('Votre compte à bien été crée.');
                        }
                    );
                    return;
                }
                return errorMessage('Vos deux mot de passe ne correspondent pas.');
            }
            return errorMessage('Veuillez entrer une adresse mail valide.');
        }
        return errorMessage('Veuillez remplir tout les champs.');
    });

    /**
     * Validate email with regex test
     * @param email
     * @return {boolean}
     */
    function validateEmail(email) {
        const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }

    /**
     * Send error notifications
     * @param msg
     * @return {*}
     */
    function errorMessage(msg) {
        return Swal.fire({
            icon: 'error',
            title: 'Erreur',
            text: msg
        })
    }

    /**
     * Send success notifications
     * @param msg
     * @return {*}
     */
    function successMessage(msg) {
        return Swal.fire({
            icon: 'success',
            title: 'Success',
            text: msg
        })
    }
</script>