<div class="header">
    <div class="headerText">
        <h1 class="regularText">Liste des chapitres</h1>
    </div>
    <img src="assets/imgs/library.jpg" alt="library">
</div>
<div class="chaptersList">
    <div class="chapterCard">
        <img src="assets/imgs/alaska.jpg" class="capterCardBackground" alt="image de fond du chapitre">
        <div class="chapterCardHeader">
            <span class="regularText">Chapitre 1 - <span class="lightText">27/08/2020</span></span>
        </div>
        <div class="chapterCardTitle">
            <h2 class="regularText">"Laissant son frère comme en secret"</h2>
        </div>
    </div>
</div>