<?php
/** @var $tickets array */
?>
<div class="header">
    <div class="headerText">
        <h1 class="regularText">Liste des chapitres</h1>
    </div>
    <img src="<?php echo $this->getHost() ?>/assets/imgs/library.jpg" alt="library">
</div>
<div class="chaptersList">
    <?php foreach ($tickets as $ticket): ?>
        <a href="<?php echo $this->getHost() ?>/chapters/<?php echo $ticket['id'] ?>">
            <div style="background-image: url('uploads/chapter_<?php echo $ticket['chapter'] ?>.png')" class="chapterCard">
                <div class="chapterCardHeader">
                    <span class="regularText">Chapitre <?php echo $ticket['chapter'] ?> - <span class="lightText"><?php echo date("d/m/Y", $ticket['date_public']);  ?></span></span>
                </div>
                <div class="chapterCardTitle">
                    <h2 class="regularText">"<?php echo $ticket['title'] ?>"</h2>
                </div>
            </div>
        </a>
    <?php endforeach; ?>
</div>