<?php
/** @var $tickets array */
/** @var $ticket array */
/** @var $isAdmin boolean */
/** @var $currentPage int */
if (!isset($currentPage)) $currentPage = 1;
if ($currentPage === 1) {
    $prevPage = 1;
} else {
    $prevPage = $currentPage - 1;
}
?>
<div class="header">
    <?php if ($viewTicket = isset($ticket)): ?>
        <div class="headerText">
            <h1 class="regularText"><?php echo $ticket['title'] ?></h1>
            <h3 class="regularText">Chapitre <?php echo $ticket['chapter'] ?></h3>
        </div>
        <img src="<?php echo $this->getHost() ?>/uploads/chapter_<?php echo $ticket['chapter'] ?>.png" alt="library">
    <?php else: ?>
        <div class="headerText">
            <h1 class="regularText">Liste des chapitres</h1>
        </div>
        <img src="<?php echo $this->getHost() ?>/assets/imgs/library.jpg" alt="library">
    <?php endif; ?>
</div>
<div class="chaptersList">
    <?php if (!$viewTicket): ?>
        <?php foreach ($tickets as $ticket): ?>
            <a href="<?php echo $this->getHost() ?>/chapters/<?php echo $ticket['id'] ?>">
                <div style="background-image: url('<?php echo $this->getHost() ?>/uploads/chapter_<?php echo $ticket['chapter'] ?>.png')"
                     class="chapterCard">
                    <div class="chapterCardHeader">
                        <span class="regularText">Chapitre <?php echo $ticket['chapter'] ?> - <span
                                    class="lightText"><?php echo date("d/m/Y", $ticket['date_public']); ?></span></span>
                    </div>
                    <div class="chapterCardTitle">
                        <h2 class="regularText">"<?php echo $ticket['title'] ?>"</h2>
                    </div>
                </div>
            </a>
        <?php endforeach; ?>
        <div class="pagination">
            <a href="<?php echo $this->getHost() ?>/chapters/page/<?php echo $prevPage ?>">
                <div class="page" tooltip="Précedent">
                    <img src="<?php echo $this->getHost(); ?>/assets/imgs/icons/leftArrow.png" alt="left arrow">
                </div>
            </a>
            <a href="<?php echo $this->getHost() ?>/chapters/page/<?php echo $currentPage + 1 ?>">
                <div class="page" tooltip="Suivant">
                    <img src="<?php echo $this->getHost(); ?>/assets/imgs/icons/rightArrow.png" alt="right arrow">
                </div>
            </a>
        </div>
    <?php else: ?>
        <div class="chapterHeader">
            <h4 tooltip="Temps estimé pour la lecture" class="readTime lightText"><?php echo $readTime ?></h4>
            <h1 class="regularText"><?php echo $ticket['title'] ?></h1>
        </div>
        <div class="chapterReadContent">
            <?php echo $ticket['content'] ?>
        </div>
        <div class="commentContainer">
            <h1 class="regularText">Commentaires</h1>
            <?php if (isset($comments)): ?>
                <?php foreach ($comments as $comment): ?>
                    <div class="commentCard">
                        <div class="commentCardLeft">
                            <img src="<?php echo $this->getHost() ?>/assets/avatar/avatar.png">
                            <div class="commentCardinfos">
                                <span class="regularText"><?php echo ucfirst($comment['author']['username']); ?></span>
                                <span class="lightText small italic">Ecrit le <?php echo date('d/m/Y',
                                        $comment['date_public']) ?></span>
                                <span class="lightText small italic">à <?php echo date('H:i:s',
                                        $comment['date_public']) ?></span>
                            </div>
                        </div>
                        <div class="commentCardRight">
                            <?php echo $comment['comment']; ?>
                        </div>
                        <div class="commentCardCommands">
                            <div id="reportComment" class="logo" tooltip="Signaler le commentaire" data-comment-id="<?php echo $comment['id'] ?>">
                                <img src="<?php echo $this->getHost() ?>/assets/imgs/icons/report.png" alt="Report">
                            </div>
                            <?php if ($isAdmin || $comment['isAuthor']): ?>
                                <div id="deleteComment" class="logo" tooltip="Supprimer le commentaire" data-comment-id="<?php echo $comment['id'] ?>">
                                    <img src="<?php echo $this->getHost() ?>/assets/imgs/icons/trash.png" alt="Trash">
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <div class="formContainer">
                <div class="formSection">
                    <h2 class="formSectionTitle regularText">Ecrire un commentaire</h2>
                    <textarea id="comment" class="textarea" placeholder="Commentaire"></textarea>
                    <p class="help">
                        - Veuillez rester respectueux et utiliser un language correct.
                    </p>
                </div>
                <div id="publish" class="buttonContainer">
                    Publier
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<script>
    // Click on "publier"
    $('#publish').click(function () {
        let comment = $('#comment').val();
        if (comment) {
            $.post('',
                {
                    action: 'create',
                    comment: comment,
                    ticketId: <?php echo $viewTicket ? $ticket["id"] : null ?>
                },
                function (msg) {
                    if (msg) return errorMessage(msg);
                    successMessage('Votre commentaire à bien été ajouté').then(() => {
                        location.reload();
                    })
                }
            );
        }
        return errorMessage('Veuillez écrire un commentaire.');
    });

    // Report comment
    $(document).on("click", "#reportComment", function () {
        Swal.fire({
            title: 'Êtes-vous sûr de vouloir signaler le commentaire ?',
            text: "Nos équipes vont analyser le commentaire",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Oui, signalez-le!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.post('',
                    {
                        action: 'report',
                        commentId: $(this).attr('data-comment-id')
                    },
                    function (msg) {
                        if (msg) return errorMessage(msg);
                        return successMessage('Le commentaire à bien été signalé');
                    }
                );
            }
        });
    });

    $(document).on("click", "#deleteComment", function () {
        Swal.fire({
            title: 'Êtes-vous sûr de vouloir supprimer le commentaire ?',
            text: "Vous ne pourrez pas revenir en arrière",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Oui, supprimez-le!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.post('',
                    {
                        action: 'delete',
                        commentId: $(this).attr('data-comment-id')
                    },
                    function (msg) {
                        if (msg) return errorMessage(msg);
                        successMessage('Le commentaire à bien été supprimé').then(() => {
                            location.reload();
                        });
                    }
                );
            }
        });
    });

    /**
     * Send error notifications
     * @param msg
     * @return {*}
     */
    function errorMessage(msg) {
        return Swal.fire({
            icon: 'error',
            title: 'Erreur',
            html: msg
        })
    }

    /**
     * Send success notifications
     * @param msg
     * @return {*}
     */
    function successMessage(msg) {
        return Swal.fire({
            icon: 'success',
            title: 'Success',
            text: msg
        })
    }
</script>