<header class="header">
    <div class="headerText">
        <h1 class="regularText">"Billet simple pour l'Alaska"</h1>
        <h3 class="regularText">Le nouveau roman de Jean Forteroche.</h3>
    </div>
    <img src="<?php echo $this->getHost() ?>/assets/imgs/alaska.jpg" alt="alaska">
</header>
<div class="homeContainer">
    <div class="bubbleImg">
        <img src="<?php echo $this->getHost() ?>/assets/imgs/jean-forteroche.jpg" alt="Jean Forteroche">
    </div>
    <h2 class="homeContainerTitle regularText">Jean Forteroche</h2>
    <div class="authorDescription">
        <p class="lightText">
            Né le 17 mai 1972 à Paris, Jean Forteroche découvra rapidement la poésie puisque sa mère, très cultivée et parlant plusieurs langues, est passionnée de théâtre. Jean Forteroche se prend de passion rapidement pour la littérature, consacrant tout son temps libre à dévorer des livres à la bibliothèque de son école. Grâce à un concours de nouvelles proposé par son professeur de français, il découvre le bonheur de l'écriture. À compter de ce jour, il ne cessera plus de noircir les pages de carnets.
            <br/>
            <br/>
            À 22 ans, il souhaite enrichir son imagination et décide donc de quitter la France pour s'exiler quelques temps aux États-Unis. Ce long voyage, ses rencontres, développeront chez lui des projets de roman. En 2003, il écrira son premier roman : "Le champ du feu", mais c'est le suivant, "Un jour viendra..." qui consacre sa rencontre avec le public. Aujour'hui, Jean revient avec un nouveau roman "Billet simple pour l'Alaska" inspiré par ses vacances passées en Alaska. Jean décide cette fois de mettre en avant première, son livre sur le web. Mais pas de panique, une édition est prévue d'ici la fin de l'année 2019 pour ceux et celles qui désirent tourner les pages d'un livre.
        </p>
    </div>
</div>