<footer class="footer">
    <div class="centerText">
        <h3 class="regularText">© <?php echo date('Y') ?> - Tout droits réservés</h3>
        <h3 class="regularText">Site réalisé par Vincent Vaufrey.</h3>
    </div>
</footer>
<script>
    const navBarResponsive = $('.navBarResponsive');
    $('.navBarBurger').click(function () {
        if (navBarResponsive.css('display') === "none") {
            navBarResponsive.css('display', 'flex');
        } else {
            navBarResponsive.hide();
        }
    });
</script>
</body>
</html>