<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, minimum-scale=0.8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="node_modules/sweetalert2/dist/sweetalert2.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="node_modules/sweetalert2/dist/sweetalert2.all.js"></script>
</head>
<body>
    <div class="navBar">
        <div class="navBarLeft">
            <a class="regularText" href="/">Jean Forteroche</a>
        </div>
        <div class="navBarRight">
            <a class="regularText" href="./">Accueil</a>
            <a class="regularText" href="./chapters">Chapitres</a>
            <a class="regularText" href="./account">Connexion</a>
        </div>
    </div>