<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8, minimum-scale=0.8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->getHost() ?>/assets/css/style.css">
    <link rel="stylesheet" href="<?php echo $this->getHost() ?>/assets/css/tooltip.css">
    <link rel="stylesheet" href="<?php echo $this->getHost() ?>/node_modules/sweetalert2/dist/sweetalert2.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="<?php echo $this->getHost() ?>/node_modules/sweetalert2/dist/sweetalert2.all.js"></script>
    <script src='https://cdn.tiny.cloud/1/2upwef5wlb6pswqf5pw4zf78o8yyrbik9oa05xhzgemhdb05/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
</head>
<body>
    <div class="navBar">
        <div class="navBarLeft">
            <a class="regularText" href="/">Jean Forteroche</a>
        </div>
        <div class="navBarRight">
            <a href="<?php echo $this->getHost() ?>">Accueil</a>
            <a href="<?php echo $this->getHost() ?>/chapters">Chapitres</a>
            <?php if ($this->isLogin()): ?>
                <a href="<?php echo $this->getHost() ?>/account">Mon compte</a>
            <?php else: ?>
                <a href="<?php echo $this->getHost() ?>/account">Connexion</a>
            <?php endif; ?>
        </div>
    </div>